#Source
  #https://cloud.google.com/appengine/docs/standard/nodejs/config/appref?hl=es-419
  # nodejs16, la versión ha cambiado desde la última actualización.
  # Buscar qué hace falta para un servidor de nodejs exactamente.
runtime: nodejs14 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# https://www.magalix.com/blog/nodejs-app-sample-from-docker-to-kubernetes-cluster

  apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodongo
        image: zarakmughal/nodejs-starter:1.0
        ports:
        - containerPort: 3000